replicaCount: 1

image:
  repository: cr.yandex/crp65onqb70atvggsqot/cartservice
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7070
  name: grpc

env:
  - name: REDIS_ADDR
    value: "rc1b-e837npt1m4p3oksq.mdb.yandexcloud.net:6379"
  - name: REDIS_PASSWD
    valueFrom:
        secretKeyRef:
          name: redis-cred
          key: redis-passwd

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
