replicaCount: 1

image:
  repository: cr.yandex/crp65onqb70atvggsqot/cartservice
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7070
  name: grpc

env:
  - name: REDIS_ADDR
    value: "rc1b-t075gfh5a1n8e0b8.mdb.yandexcloud.net:6379,password=password"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
