apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendationservice.fullname" . }}
  labels:
    {{- include "recommendationservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "recommendationservice.selectorLabels" . | nindent 4 }}
